services:
  nordvpn:
    container_name: GlueTun-Nord
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - "8082:8082" # QbitTorrent UI
      - "9091:9091" # Transmission
      - "51413:51413" # Transmision
      - "51413:51413/udp" # Transmision
      - "51420:51420" # QbitTorrent
      - "51420:51420/udp" # QbitTorrent
#      - "8085:8081" #metube
      - "8080:8080" # OpenWebUI
      - "11434:11434" # Ollama
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${NORD_U}
      - OPENVPN_PASSWORD=${NORD_P}
      - SERVER_REGIONS=Poland
      - VPN_TYPE=openvpn
      - FIREWALL_OUTBOUND_SUBNETS=192.168.8.0/24
    networks:
      - mariusz-network
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:nordvpn"
    container_name: QbitTorrent-Nord
    depends_on:
      - nordvpn
      - swag
    environment:
      - WEBUI_PORT=8082
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/qbittorrent:/config
      - ${ROOT_DATA_HDD}:/hdd
      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai_comics
      - ${ROOT_DATA_SSD}:/ssd
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/metube:/config
      - ${ROOT_DATA_HDD}:/hdd
      - "/etc/localtime:/etc/localtime:ro"
    ports:
        - 8085:8081
    networks:
      - mariusz-network
    depends_on:
      - swag

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/sonarr:/config
      - ${ROOT_DATA_HDD}:/hdd
    ports:
      - 8989:8989
    networks:
      - mariusz-network
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/radarr:/config
      - ${ROOT_DATA_HDD}:/hdd
    ports:
      - 7878:7878
    networks:
      - mariusz-network
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/bazarr:/config
      - ${ROOT_DATA_HDD}:/hdd
    ports:
      - 6767:6767
    networks:
      - mariusz-network
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${ROOT_APPDATA}/jellyseerr:/app/config
    networks:
      - mariusz-network
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      URL: januszex.net
      SUBDOMAINS: >
        www,
        bazarr,
        radarr,
        sonarr,
        qbittorrent,
        nextcloud,
        jellyfin,
        ombi,
        comicstreamer,
        prowlarr,
        xbvr,
        accounts,
        whisparr,
        metube,
        transmission,
        sabnzbd,
        duplicati,
        vue,
        files,
        openwebui,
        chat,
        czat,
        jellyseerr,
        requests,
        portainer,
        reiverr,
        stash,
        coomarr,
        vaultwarden
      VALIDATION: http
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    networks:
      - mariusz-network
    restart: unless-stopped

  docker-host:
    image: qoomon/docker-host
    container_name: docker-host
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - mariusz-network
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - FFMPEG_ANALYZEDURATION=400M
      - FFMPEG_PROBESIZE=2G
    volumes:
      - ${ROOT_APPDATA}/jellyfin:/config
      - ${ROOT_APPDATA}/jellyfin/config.json:/usr/share/jellyfin/web/config.json
      - ${ROOT_MEDIA}:/media
    ports:
      - 8097:8096
    networks:
      - mariusz-network
    devices:
      - "/dev/dri:/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [video]
    restart: unless-stopped

  comicstreamer:
    container_name: comicstreamer
    image: mateuszkukiela/comicstreamer:latest
    volumes:
      - ${ROOT_APPDATA}/comicstreamer:/config
      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai
    ports:
      - 32500:32500
    networks:
      - mariusz-network
    restart: unless-stopped

  prowlarr:
      image: ghcr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      volumes:
        - ${ROOT_APPDATA}/prowlarr:/config
      ports:
        - 9696:9696
      networks:
        - mariusz-network
      restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/sabnzbd:/config
      - ${ROOT_DATA_HDD}:/hdd
      - ${ROOT_DATA_SSD}:/ssd
    ports:
      - 8089:8080
    networks:
      - mariusz-network
    restart: unless-stopped

  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    environment:
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/authelia:/config
    networks:
      - mariusz-network
    restart: unless-stopped

  jfa:
      container_name: jfa
      ports:
          - "8056:8056"
      volumes:
          - ${ROOT_APPDATA}/jfa-go:/data
          - ${ROOT_APPDATA}/jellyfin:/jf
          - '/etc/localtime:/etc/localtime:ro'
      image: hrfee/jfa-go
      restart: unless-stopped
      networks:
          - mariusz-network

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
        - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - ${ROOT_APPDATA}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mariusz-network
    restart: unless-stopped

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/duplicati/config:/config
      - ${ROOT_BACKUPS}:/backups
      - ${ROOT_MARIUSZ}:/source
    ports:
      - 8200:8200
    networks:
      - mariusz-network
    restart: unless-stopped

  jf-vue:
    image: jellyfin/jellyfin-vue:unstable
    container_name: "jellyfin-vue-client"
    stdin_open: true
    tty: true
    ports:
      - 3831:80
    restart: unless-stopped
    environment:
      - DEFAULT_SERVERS=https://jellyfin.januszex.net
    networks:
      - mariusz-network

  filebrowser:
    container_name: filebrowser
    volumes:
        - ${ROOT_APPDATA}/filebrowser/filebrowser.db:/database/filebrowser.db
        - ${ROOT_APPDATA}/filebrowser/settings.json:/config/settings.json
        - ${ROOT_DATA_HDD}:/hdd
        - ${ROOT_DATA_SSD}:/ssd
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    ports:
        - 8250:80
    image: filebrowser/filebrowser:s6
    networks:
      - mariusz-network
    restart: unless-stopped

  openwebui:
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
        - ${ROOT_APPDATA}/openwebui:/app/backend/data
    container_name: openwebui
    restart: always
    image: ghcr.io/open-webui/open-webui:cuda
    network_mode: "service:nordvpn"

  ollama:
    volumes:
      - ${ROOT_SSD}/ollama:/root/.ollama
    container_name: ollama
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    network_mode: "service:nordvpn"
    restart: unless-stopped

#  whisperasr:
#    container_name: whisperasr
#    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
#    environment:
#      - ASR_MODEL=small
#      - ASR_ENGINE=faster_whisper
#    ports:
#      - 9000:9000
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
#    restart: no
#    networks:
#      - mariusz-network

  reiverr:
    image: ghcr.io/aleksilassila/reiverr:latest
    container_name: reiverr
    ports:
      - 9494:9494
    environment:
      - SECRET=${REIVERR_SECRET}
      - ADMIN_USERNAME=root
      - ADMIN_PASSWORD=${PASSWORD}
    volumes:
      - ${ROOT_APPDATA}/reiverr:/config
    restart: unless-stopped
    networks:
        - mariusz-network

  stash:
    image: ghcr.io/feederbox826/stash-s6:hwaccel
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT_APPDATA}/stash/metadata:/metadata
      - ${ROOT_APPDATA}/stash/config:/config
      - ${ROOT_APPDATA}/stash//pip-install:/pip-install
      - ${ROOT_SSD}/stash/cache:/cache
      - ${ROOT_SSD}/stash/blobs:/blobs
      - ${ROOT_SSD}/stash/generated:/generated
      - ${ROOT_DATA_HDD}:/hdd
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: >
      /bin/bash -c "pip install --user --break-system-packages emojis requests lxml stashapp-tools &&
                    exec /bin/bash /opt/entrypoint.sh"
    networks:
        - mariusz-network

  coomarr:
    image: mateuszkukiela/coomarr
    container_name: coomarr
    ports:
      - 42069:42069
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/coomarr:/config
      - ${ROOT_MEDIA}/porn/coomarr:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    networks:
      - mariusz-network


  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      DOMAIN: "https://vaultwarden.januszex.net"
      SIGNUPS_ALLOWED: false
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    volumes:
      - ${ROOT_APPDATA}/vaultwarden:/data/
    ports:
      - 8260:80
    restart: unless-stopped
    networks:
      - mariusz-network

      
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    networks:
      - mariusz-network
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      LOG_LEVEL: INFO

      ## Features
      REMOVE_TIMER: 10
      REMOVE_FAILED: True
      REMOVE_FAILED_IMPORTS: True
      REMOVE_METADATA_MISSING: True
      REMOVE_MISSING_FILES: True
      REMOVE_ORPHANS: True
      REMOVE_SLOW: True
      REMOVE_STALLED: True
      REMOVE_UNMONITORED: True
      RUN_PERIODIC_RESCANS: '
        {
        "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
        "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'

      # Feature Settings
      PERMITTED_ATTEMPTS: 3
      NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
      MIN_DOWNLOAD_SPEED: 100
      FAILED_IMPORT_MESSAGE_PATTERNS: '
        [
        "Not a Custom Format upgrade for existing",
        "Not an upgrade for existing"
        ]'

      ## Radarr
      RADARR_URL: https://radarr.januszex.net
      RADARR_KEY: ${RADARR_API_KEY}

      ## Sonarr
      SONARR_URL: https://sonarr.januszex.net
      SONARR_KEY: ${SONARR_API_KEY}

      ## qBitorrent
      QBITTORRENT_URL: https://qbittorrent.januszex.net
      QBITTORRENT_USERNAME: root
      QBITTORRENT_PASSWORD: ${PASSWORD}


networks:
  mariusz-network:
