---
services:
    authelia:
        image: authelia/authelia:4.21.0
        container_name: authelia
        environment:
            - TZ=${TZ}
        volumes:
            - ${ROOT_APPDATA}/authelia:/config
        networks:
            - mariusz-network
        restart: unless-stopped

    bazarr:
        image: ghcr.io/linuxserver/bazarr
        container_name: bazarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022
        volumes:
            - ${ROOT_APPDATA}/bazarr:/config
            - ${ROOT_METADATA}/bazarr/log:/config/log
            - ${ROOT_DATA_HDD}:/hdd
        ports:
            - 6767:6767
        networks:
            - mariusz-network
        restart: unless-stopped

    broker:
        image: docker.io/library/redis:7
        volumes:
            - redisdata:/data
        networks:
            - mariusz-network
        restart: unless-stopped

    comicstreamer:
        container_name: comicstreamer
        image: mateuszkukiela/comicstreamer:latest
        volumes:
            - ${ROOT_APPDATA}/comicstreamer:/config
            - ${ROOT_METADATA}/comicstreamer/logs:/config/logs
            - ${ROOT_DATA_HDD}:/hdd
        ports:
            - 32500:32500
        networks:
            - mariusz-network
        restart: unless-stopped

    database:
        container_name: immich_postgres
        image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
            POSTGRES_INITDB_ARGS: --data-checksums
        volumes:
            - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
        healthcheck:
            test: >-
                pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
                Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}"
                --tuples-only --no-align
                --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
                echo "checksum failure count is $$Chksum";
                [ "$$Chksum" = '0' ] || exit 1
            interval: 5m
            start_interval: 30s
            start_period: 5m
        command: >-
            postgres
            -c shared_preload_libraries=vectors.so
            -c 'search_path="$$user", public, vectors'
            -c logging_collector=on
            -c max_wal_size=2GB
            -c shared_buffers=512MB
            -c wal_compression=on
        networks:
            - mariusz-network
        restart: always

    db:
        image: docker.io/library/postgres:15
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: paperless
            POSTGRES_USER: paperless
            POSTGRES_PASSWORD: ${PASSWORD}
        networks:
            - mariusz-network
        restart: unless-stopped

    debilarr:
        container_name: debilarr
        image: mateuszkukiela/debilarr:latest
        restart: unless-stopped
        environment:
            JELLYFIN_URL: https://jellyfin.januszex.net
            JELLYFIN_API_KEY: ${JELLYFIN_API_KEY}
            SAB_URL: https://sabnzbd.januszex.net
            SAB_API_KEY: ${SAB_API_KEY}
            INTERVAL: '30'
            RESUME_COOLDOWN: '60'
            INCLUDE_PAUSED: 'false'
            LOG_LEVEL: INFO
        depends_on:
            - jellyfin
            - sabnzbd

    decluttarr:
        image: ghcr.io/manimatter/decluttarr:latest
        container_name: decluttarr
        restart: always
        networks:
            - mariusz-network
        environment:
            TZ: ${TZ}
            PUID: ${PUID}
            PGID: ${PGID}
            LOG_LEVEL: INFO
            REMOVE_TIMER: 10
            REMOVE_FAILED: true
            REMOVE_FAILED_IMPORTS: true
            REMOVE_METADATA_MISSING: true
            REMOVE_MISSING_FILES: true
            REMOVE_ORPHANS: true
            REMOVE_SLOW: true
            REMOVE_STALLED: true
            REMOVE_UNMONITORED: true
            RUN_PERIODIC_RESCANS: ' { "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}, "RADARR":
                {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7} }'
            PERMITTED_ATTEMPTS: 3
            NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
            MIN_DOWNLOAD_SPEED: 100
            FAILED_IMPORT_MESSAGE_PATTERNS: ' [ "Not a Custom Format upgrade for existing", "Not an upgrade for existing" ]'
            RADARR_URL: https://radarr.januszex.net
            RADARR_KEY: ${RADARR_API_KEY}
            SONARR_URL: https://sonarr.januszex.net
            SONARR_KEY: ${SONARR_API_KEY}
            QBITTORRENT_URL: https://qbittorrent.januszex.net
            QBITTORRENT_USERNAME: root
            QBITTORRENT_PASSWORD: ${PASSWORD}



    filebrowser:
        container_name: filebrowser
        image: filebrowser/filebrowser:s6
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${ROOT_APPDATA}/filebrowser/filebrowser.db:/database/filebrowser.db
            - ${ROOT_APPDATA}/filebrowser/settings.json:/config/settings.json
            - ${ROOT_DATA_HDD}:/srv/hdd
            - ${ROOT_DATA_SSD}:/srv/ssd
        ports:
            - 8250:80
        networks:
            - mariusz-network
        restart: unless-stopped

    gotenberg:
        image: docker.io/gotenberg/gotenberg:7.10
        command:
            - gotenberg
            - --chromium-disable-javascript=true
            - --chromium-allow-list=file:///tmp/.*
        networks:
            - mariusz-network
        restart: unless-stopped

    immich-machine-learning:
        container_name: immich_machine_learning
        image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
        volumes:
            - model-cache:/cache
        env_file:
            - .env
        networks:
            - mariusz-network
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        healthcheck:
            disable: false
        restart: always

    immich-server:
        container_name: immich_server
        image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
        volumes:
            - ${UPLOAD_LOCATION}:/usr/src/app/upload
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - .env
        ports:
            - 2283:2283
        depends_on:
            - redis
            - database
        networks:
            - mariusz-network
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        healthcheck:
            disable: false
        restart: always

    idiotarr:
        image: ghcr.io/mateuszkukiela/idiotarr:latest
        container_name: idiotarr
        environment:
            - PROWLARR_URL=${PROWLARR_URL}
            - PROWLARR_API_KEY=${PROWLARR_API_KEY}
            - FRESH_DAYS=30
            - FRESH_TAG=NZB-FRESH
            - TORRENT_TAG=TORRENT-LAST-RESORT
        ports:
            - 9797:9797
        networks:
            - mariusz-network
        restart: unless-stopped

    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
            - NVIDIA_VISIBLE_DEVICES=all
            - FFMPEG_ANALYZEDURATION=400M
            - FFMPEG_PROBESIZE=2G
            - LD_LIBRARY_PATH=/usr/lib/wsl/lib
        volumes:
            - ${ROOT_APPDATA}/jellyfin:/config
            - ${ROOT_APPDATA}/jellyfin/config.json:/usr/share/jellyfin/web/config.json
            - ${ROOT_METADATA}/jellyfin/data:/config/data
            - ${ROOT_METADATA}/jellyfin/cache:/config/cache
            - ${ROOT_METADATA}/jellyfin/log:/config/log
            - ${ROOT_DATA_HDD}:/hdd
            - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
            - /home/mariusz/wsl_drivers_new/nv_dispi.inf_amd64_4bf4c17fa8a478b5:/usr/lib/wsl/drivers/nv_dispi.inf_amd64_4bf4c17fa8a478b5:ro
        ports:
            - 8097:8096
        devices:
            - /dev/dri:/dev/dri
            - /dev/dxg:/dev/dxg
        networks:
            - mariusz-network
        restart: unless-stopped

    jellyseerr:
        image: ghcr.io/seerr-team/seerr:latest
        init: true
        container_name: jellyseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=${TZ}
        ports:
            - 5055:5055
        volumes:
            - ${ROOT_APPDATA}/jellyseerr:/app/config
            - ${ROOT_METADATA}/jellyseerr/logs:/app/config/logs
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
            start_period: 20s
            timeout: 3s
            interval: 15s
            retries: 3
        networks:
            - mariusz-network
        restart: unless-stopped

    jfa:
        container_name: jfa
        image: hrfee/jfa-go
        ports:
            - 8056:8056
        volumes:
            - ${ROOT_APPDATA}/jfa-go:/data
            - ${ROOT_APPDATA}/jellyfin:/jf
            - ${ROOT_METADATA}/jellyfin/data:/jf/data
            - /etc/localtime:/etc/localtime:ro
        networks:
            - mariusz-network
        restart: unless-stopped



    metube:
        image: ghcr.io/alexta69/metube
        container_name: metube
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${ROOT_APPDATA}/metube:/config
            - ${ROOT_DATA_HDD}:/hdd
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8085:8081
        networks:
            - mariusz-network
        restart: unless-stopped


    paperless:
        container_name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        depends_on:
            - db
            - broker
            - gotenberg
            - tika
        ports:
            - 8000:8000
        volumes:
            - ${ROOT_APPDATA}/paperless/data:/usr/src/paperless/data
            - ${ROOT_MEDIA}/paperless/media:/usr/src/paperless/media
            - ${ROOT_MEDIA}/paperless/export:/usr/src/paperless/export
            - ${ROOT_MEDIA}/paperless/consume:/usr/src/paperless/consume
        environment:
            USERMAP_UID: ${PUID}
            USERMAP_GID: ${PGID}
            PAPERLESS_OCR_LANGUAGES: pol
            PAPERLESS_URL: https://paperless.januszex.net
            PAPERLESS_SECRET_KEY: ${REIVERR_SECRET}
            PAPERLESS_TIME_ZONE: ${TZ}
            PAPERLESS_OCR_LANGUAGE: pol
            PAPERLESS_REDIS: redis://broker:6379
            PAPERLESS_DBHOST: db
            PAPERLESS_DBPASS: ${PASSWORD}
            PAPERLESS_TIKA_ENABLED: 1
            PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
            PAPERLESS_TIKA_ENDPOINT: http://tika:9998
            PAPERLESS_FILENAME_FORMAT: '{owner_username}/{correspondent}/{created year}/{created} {title} ({correspondent}'
        networks:
            - mariusz-network
        restart: unless-stopped

    portainer:
        container_name: portainer
        image: portainer/portainer-ce:latest
        ports:
            - 9443:9443
        volumes:
            - ${ROOT_APPDATA}/portainer:/data
            - ${ROOT_METADATA}/portainer/backups:/data/backups
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - mariusz-network
        restart: unless-stopped

    profilarr:
        image: santiagosayshey/profilarr:latest
        container_name: profilarr
        ports:
            - 6868:6868
        volumes:
            - ${ROOT_APPDATA}/profilarr:/config
            - ${ROOT_METADATA}/profilarr/backups:/config/backups
            - ${ROOT_METADATA}/profilarr/log:/config/log
        environment:
            - TZ=${TZ}
        networks:
            - mariusz-network
        restart: unless-stopped

    prowlarr:
        image: ghcr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${ROOT_APPDATA}/prowlarr:/config
            - ${ROOT_METADATA}/prowlarr/Backups:/config/Backups
            - ${ROOT_METADATA}/prowlarr/logs:/config/logs
        ports:
            - 9696:9696
        networks:
            - mariusz-network
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - WEBUI_PORT=8082
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${ROOT_APPDATA}/qbittorrent:/config
            - ${ROOT_DATA_HDD}:/hdd
            - ${ROOT_DATA_SSD}:/ssd
        ports:
            - 8082:8082
            - 6881:6881
            - 6881:6881/udp
        networks:
            - mariusz-network
        restart: unless-stopped

    radarr:
        image: ghcr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${ROOT_APPDATA}/radarr:/config
            - ${ROOT_METADATA}/radarr/MediaCover:/config/MediaCover
            - ${ROOT_METADATA}/radarr/Backups:/config/Backups
            - ${ROOT_METADATA}/radarr/logs:/config/logs
            - ${ROOT_DATA_HDD}:/hdd
        ports:
            - 7878:7878
        networks:
            - mariusz-network
        restart: unless-stopped

    redis:
        container_name: immich_redis
        image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
        healthcheck:
            test: redis-cli ping || exit 1
        networks:
            - mariusz-network
        restart: always


    sabnzbd:
        image: lscr.io/linuxserver/sabnzbd:latest
        container_name: sabnzbd
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${ROOT_APPDATA}/sabnzbd:/config
            - ${ROOT_METADATA}/sabnzbd/logs:/config/logs
            - ${ROOT_DATA_HDD}:/hdd
            - ${ROOT_DATA_SSD}:/ssd
        ports:
            - 8089:8080
        networks:
            - mariusz-network
        restart: unless-stopped

    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022
        volumes:
            - ${ROOT_APPDATA}/sonarr:/config
            - ${ROOT_METADATA}/sonarr/MediaCover:/config/MediaCover
            - ${ROOT_METADATA}/sonarr/Backups:/config/Backups
            - ${ROOT_METADATA}/sonarr/logs:/config/logs
            - ${ROOT_DATA_HDD}:/hdd
        ports:
            - 8989:8989
        networks:
            - mariusz-network
        restart: unless-stopped

    stash:
        image: ghcr.io/feederbox826/stash-s6:hwaccel
        container_name: stash
        environment:
            - STASH_STASH=/data/
            - STASH_GENERATED=/generated/
            - STASH_METADATA=/metadata/
            - STASH_CACHE=/cache/
            - STASH_PORT=9999
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${ROOT_APPDATA}/stash/metadata:/metadata
            - ${ROOT_APPDATA}/stash/config:/config
            - ${ROOT_APPDATA}/stash//pip-install:/pip-install
            - ${ROOT_SSD}/stash/cache:/cache
            - ${ROOT_SSD}/stash/blobs:/blobs
            - ${ROOT_SSD}/stash/generated:/generated
            - ${ROOT_DATA_HDD}:/hdd
        ports:
            - 9999:9999
        logging:
            driver: json-file
            options:
                max-file: '10'
                max-size: 2m
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        command: >
            /bin/bash -c "pip install --user --break-system-packages emojis requests lxml stashapp-tools &&
                          exec /bin/bash /opt/entrypoint.sh"
        networks:
            - mariusz-network
        restart: unless-stopped

    streamyfin:
        container_name: streamyfin
        image: fredrikburmester/streamyfin-optimized-versions-server:master
        environment:
            - NODE_ENV=development
        env_file:
            - .env
        ports:
            - 3000:3000
        volumes:
            - ${ROOT_DATA_HDD}/media/cache:/usr/src/app/cache
        networks:
            - mariusz-network
        restart: always

    caddy:
        image: ghcr.io/serfriz/caddy-cloudflare:latest
        container_name: caddy
        environment:
            - CF_API_TOKEN=${CF_API_TOKEN}
            - METUBE_PASSWORD_HASH=${METUBE_PASSWORD_HASH}
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - ${ROOT_APPDATA}/caddy/data:/data
            - ${ROOT_APPDATA}/caddy/config:/config
        ports:
            - 443:443
            - 80:80
        networks:
            - mariusz-network
        restart: unless-stopped

    tika:
        image: docker.io/apache/tika:latest
        networks:
            - mariusz-network
        restart: unless-stopped

    uptime-kuma:
        image: ghcr.io/mateuszkukiela/uptime-kuma:latest
        container_name: uptime-kuma
        volumes:
            - ${ROOT_APPDATA}/uptime-kuma:/app/data
        networks:
            - mariusz-network
        restart: unless-stopped


    watchtower:
        container_name: watchtower
        image: containrrr/watchtower
        environment:
            - WATCHTOWER_CLEANUP=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped

networks:
    mariusz-network:

volumes:
    model-cache:
    data:
    media:
    pgdata:
    redisdata:
