version: '3.3'
services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
      - PGID=${PUID}
      - PUID=${PGID}
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${ROOT_APPDATA}/homebridge:/homebridge

  alpine-qbittorrent-openvpn:
    container_name: qbittorrent
    volumes:
      - ${ROOT_APPDATA}/newqbittorrentvpn:/config
      - ${ROOT_MEDIA}/downloads:/downloads
      - ${ROOT_MEDIA}/porn:/porn
      - ${ROOT_MEDIA}/movies:/movies
      - ${ROOT_MEDIA}/tv:/tv
      - ${ROOT_MEDIA}/other:/other
      - ${ROOT_MEDIA}/hentai:/hentai
      - ${ROOT_MEDIA}/porn_vr:/porn_vr
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=PL
      - OPENVPN_USERNAME=${NORD_USER}
      - OPENVPN_PASSWORD=${NORD_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LAN=192.168.8.0/24
      - QBT_WEBUI_PORT=8080
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:development

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/sonarr:/config
      - ${ROOT_MEDIA}/tv:/tv
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/radarr:/config
      - ${ROOT_MEDIA}/movies:/movies
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/bazarr:/config
      - ${ROOT_MEDIA}/movies:/movies
      - ${ROOT_MEDIA}/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - mariadb
    volumes:
      - ${ROOT_APPDATA}/nextcloud:/config
      - ${ROOT_NEXTCLOUD}:/data
    ports:
      - 444:443
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ${ROOT_APPDATA}/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/heimdall:/config
    ports:
      - 82:80
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=januszex.net
      - SUBDOMAINS=www,bazarr,radarr,sonarr,qbittorrent,nextcloud,jellyfin,ombi,comicstreamer,truenas,bruno,photos,photoprism,prowlarr,lidarr,airsonic,readarr,calibre-web,calibre,proxy,nzbget,xbvr
      - VALIDATION=http
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  docker-host:
    image: qoomon/docker-host
    container_name: docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/jellyfin:/config
      - ${ROOT_MEDIA}/tv:/data/tv
      - ${ROOT_MEDIA}/movies:/data/movies
      - ${ROOT_MEDIA}/downloads:/downloads
      - ${ROOT_MEDIA}/porn:/data/porn
      - ${ROOT_MEDIA}/music:/music
    ports:
      - 8096:8096
    restart: unless-stopped

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=86400
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=${TZ}
    ports:
      - 8888:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gdrive-backup:
    container_name: gdrive-backup
    image: mateuszkukiela/gdrive-backup:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CRON=0 6 * * *
      - REMAIN=1
      - TEAM_ID=0AEiQ1YhMGjRfUk9PVA
    restart: unless-stopped
    volumes:
      - ./credentials:/credentials
      - ${ROOT_APPDATA}:/appdata

  comicstreamer:
    container_name: comicstreamer
    image: mateuszkukiela/comicstreamer:latest
    volumes:
      - ${ROOT_APPDATA}/comicstreamer:/config
      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai
    ports:
      - 32500:32500
    restart: unless-stopped

  prowlarr:
      image: ghcr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      volumes:
        - ${ROOT_APPDATA}/prowlarr:/config
      ports:
        - 9696:9696
      restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/lidarr:/config
      - ${ROOT_MEDIA}/music:/music
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  airsonic:
    image: ghcr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/airsonic:/config
      - ${ROOT_MEDIA}/music:/music
      - ${ROOT_MEDIA}/music/playlists:/playlists
      - ${ROOT_MEDIA}/music/podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped

  readarr:
    image: ghcr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/readarr:/config
      - ${ROOT_MEDIA}/books:/books
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${ROOT_APPDATA}/calibre-web:/config
      - ${ROOT_MEDIA}/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/calibre:/config
    ports:
      - 8082:8080
      - 8081:8081
    restart: unless-stopped

  php-proxy:
    image: dwaaan/php-proxy:latest
    restart: unless-stopped
    ports:
      - 8084:80
      - 8443:443

# TODO: Un-hardcode LAN address
  nzbgetvpn:
    container_name: nzbgetvpn
    privileged: true
    volumes:
        - ${ROOT_APPDATA}/nzbgetvpn:/config
        - ${ROOT_MEDIA}/downloads:/downloads
        - ${ROOT_MEDIA}/porn:/porn
        - ${ROOT_MEDIA}/movies:/movies
        - ${ROOT_MEDIA}/tv:/tv
        - ${ROOT_MEDIA}/other:/other
        - ${ROOT_MEDIA}/hentai:/hentai
        - ${ROOT_MEDIA}/porn_vr:/porn_vr
    environment:
        - VPN_ENABLED=wireguard
        - VPN_TYPE=openvpn
        - ENABLE_SSL=no
        - VPN_USERNAME=${NORD_USER}
        - VPN_PASSWORD=${NORD_PASSWORD}
        - WEBUI_USERNAME=root
        - WEBUI_PASSWORD=${PASSWORD}
        - PUID=${PUID}
        - PGID=${PGID}
        - LAN_NETWORK=192.168.8.10/24
        - 'NAME_SERVERS=1.1.1.1,1.0.0.1'
    ports:
        - '6789:6789'
        - '6791:6791'
    restart: unless-stopped
    image: dyonr/nzbgetvpn

  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    environment:
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/authelia:/config
    restart: unless-stopped

  xbvr:
    image: 'xbapps/xbvr:latest'
    container_name: xbvr
    volumes:
      - ${ROOT_MEDIA}/porn_vr:/videos
      - ${ROOT_APPDATA}/xbvr:/root/.config/
    ports:
      - "9999:9999"
    restart: always
    
    ebusd:
    image: 'john30/ebusd:latest'
    container_name: ebusd
    enviroment:
      - EBUSD_SCANCONFIG=192.168.8.243
      - EBUSD_MQTTPORT=1883
      - EBUSD_MQTTHOST=core-mosquitto
    ports:
      - "8888:8869"
    restart: always
