version: '3.3'
services:
#  nord:
#    container_name: nord
#    image: ghcr.io/bubuntux/nordlynx
#    restart: unless-stopped
#    security_opt:
#      - no-new-privileges:true
#    cap_add:
#      - NET_ADMIN
#    environment:
#      - PRIVATE_KEY=${NORD_KEY}
#      - ALLOWED_IPS=0.0.0.0/1,128.0.0.0/1
#      - NET_LOCAL=10.0.0.0/8,172.16.0.0/12,192.168.2.0/24
#      - QUERY=filters\[country_id\]=174&filters\[servers_groups\]\[identifier\]=legacy_p2p
#      - "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
#      - "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')"
#      - TZ=${TZ}
#    ports:
#      - 8080:8080 #qbit
#      - "51420:51420" # QbitTorrent
#      - "51420:51420/udp" # QbitTorrent
#      - "8085:8081" #metube
##      - "9091:9091" #transmission
##      - "51413:51413" #transmission
##      - "51413:51413/udp" #transmission
#    sysctls:
#      - net.ipv6.conf.all.disable_ipv6=0
#
#  qbittorrent:
#    container_name: qbittorrent
#    image: lscr.io/linuxserver/qbittorrent
#    restart: unless-stopped
#    network_mode: "service:nord"
#    environment:
#      - TZ=${TZ}
#    volumes:
#      - ${ROOT_APPDATA}/qbittorrent:/config
#      - ${ROOT_MEDIA}/downloads:/downloads
#      - ${ROOT_MEDIA}/porn:/porn
#      - ${ROOT_MEDIA}/movies:/movies
#      - ${ROOT_MEDIA}/movies4k:/movies4k
#      - ${ROOT_MEDIA}/tv:/tv
#      - ${ROOT_MEDIA}/other:/other
#      - ${ROOT_MEDIA}/hentai:/hentai
#      - ${ROOT_MEDIA}/porn_vr:/porn_vr
#      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai_comics
#      - "/etc/localtime:/etc/localtime:ro"
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
#    depends_on:
#      - nord
#      - swag

  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - ${ROOT_APPDATA}/transmissionvpn:/config
      - ${ROOT_MEDIA}/downloads:/downloads
      - ${ROOT_MEDIA}/porn:/porn
      - ${ROOT_MEDIA}/movies:/movies
      - ${ROOT_MEDIA}/movies4k:/movies4k
      - ${ROOT_MEDIA}/tv:/tv
      - ${ROOT_MEDIA}/other:/other
      - ${ROOT_MEDIA}/hentai:/hentai
      - ${ROOT_MEDIA}/porn_vr:/porn_vr
      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai_comics
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME={NORD_U}
      - OPENVPN_PASSWORD={NORD_P}
      - LOCAL_NETWORK=192.168.8.0/24
      - NORDVPN_COUNTRY=PL
      - NORDVPN_CATEGORY=legacy_p2p
    logging:
      driver: json-file
      options:
          max-size: 10m
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn


#  metube:
#    image: ghcr.io/alexta69/metube
#    container_name: metube
#    restart: unless-stopped
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${ROOT_APPDATA}/metube:/config
#      - ${ROOT_MEDIA}/downloads:/downloads/downloads
#      - ${ROOT_MEDIA}/porn:/downloads/porn
#      - ${ROOT_MEDIA}/movies:/downloads/movies
#      - ${ROOT_MEDIA}/movies4k:/downloads/movies4k
#      - ${ROOT_MEDIA}/tv:/downloads/tv
#      - ${ROOT_MEDIA}/other:/downloads/other
#      - ${ROOT_MEDIA}/hentai:/downloads/hentai
#      - ${ROOT_MEDIA}/porn_vr:/downloads/porn_vr
#      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/downloads/hentai_comics
#      - "/etc/localtime:/etc/localtime:ro"
#    network_mode: service:nord
#    depends_on:
#      - nord
#      - swag

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/sonarr:/config
      - ${ROOT_MEDIA}/tv:/tv
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - mariusz-network
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/radarr:/config
      - ${ROOT_MEDIA}/movies:/movies
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - mariusz-network
    restart: unless-stopped

  radarr4k:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr4k
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/radarr4k:/config
      - ${ROOT_MEDIA}/movies4k:/movies4k
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 7879:7878
    networks:
      - mariusz-network
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/bazarr:/config
      - ${ROOT_MEDIA}/movies:/movies
      - ${ROOT_MEDIA}/tv:/tv
    ports:
      - 6767:6767
    networks:
      - mariusz-network
    restart: unless-stopped

  ombi:
    image: ghcr.io/linuxserver/ombi:development
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/ombi:/config
    ports:
      - 3579:3579
    networks:
      - mariusz-network
    restart: unless-stopped

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - mariadb
    volumes:
      - ${ROOT_APPDATA}/nextcloud:/config
      - ${ROOT_NEXTCLOUD}:/data
    ports:
      - 444:443
    networks:
      - mariusz-network
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ${ROOT_APPDATA}/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - mariusz-network
    restart: unless-stopped

#  heimdall:
#    image: ghcr.io/linuxserver/heimdall
#    container_name: heimdall
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${ROOT_APPDATA}/heimdall:/config
#    ports:
#      - 82:80
#    networks:
#      - mariusz-network
#    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=januszex.net
      - SUBDOMAINS=www,bazarr,radarr,sonarr,qbittorrent,nextcloud,jellyfin,ombi,comicstreamer,truenas,bruno,photos,photoprism,prowlarr,lidarr,airsonic,readarr,calibre-web,calibre,proxy,nzbget,xbvr,radarr4k,konto,whisparr,metube,transmission
      - VALIDATION=http
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    networks:
      - mariusz-network
    restart: unless-stopped

  docker-host:
    image: qoomon/docker-host
    container_name: docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - mariusz-network
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/jellyfin:/config
      - ${ROOT_MEDIA}/tv:/data/tv
      - ${ROOT_MEDIA}/movies:/data/movies
      - ${ROOT_MEDIA}/movies4k:/data/movies4k
      - ${ROOT_MEDIA}/downloads:/downloads
      - ${ROOT_MEDIA}/porn:/data/porn
      - ${ROOT_MEDIA}/music:/music
      - ${ROOT_APPDATA}/jellyfin/config.json:/usr/share/jellyfin/web/config.json
    ports:
      - 8096:8096
    networks:
      - mariusz-network
    restart: unless-stopped

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=86400
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=${TZ}
    ports:
      - 8888:8080
    networks:
      - mariusz-network
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  comicstreamer:
    container_name: comicstreamer
    image: mateuszkukiela/comicstreamer:latest
    volumes:
      - ${ROOT_APPDATA}/comicstreamer:/config
      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai
    ports:
      - 32500:32500
    networks:
      - mariusz-network
    restart: unless-stopped

  prowlarr:
      image: ghcr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      volumes:
        - ${ROOT_APPDATA}/prowlarr:/config
      ports:
        - 9696:9696
      networks:
        - mariusz-network
      restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/lidarr:/config
      - ${ROOT_MEDIA}/music:/music
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 8686:8686
    networks:
      - mariusz-network
    restart: unless-stopped

  readarr:
    image: ghcr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/readarr:/config
      - ${ROOT_MEDIA}/books:/books
      - ${ROOT_MEDIA}/downloads:/downloads
    ports:
      - 8787:8787
    networks:
      - mariusz-network
    restart: unless-stopped

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${ROOT_APPDATA}/calibre-web:/config
      - ${ROOT_MEDIA}/books:/books
    ports:
      - 8083:8083
    networks:
      - mariusz-network
    restart: unless-stopped

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/calibre:/config
    ports:
      - 8082:8080
      - 8081:8081
    networks:
      - mariusz-network
    restart: unless-stopped

  php-proxy:
    image: dwaaan/php-proxy:latest
    restart: unless-stopped
    ports:
      - 8084:80
      - 8443:443
    networks:
      - mariusz-network

# TODO: Un-hardcode LAN address
  nzbgetvpn:
    container_name: nzbgetvpn
    privileged: true
    volumes:
        - ${ROOT_APPDATA}/nzbgetvpn:/config
        - ${ROOT_MEDIA}/downloads:/downloads
        - ${ROOT_MEDIA}/porn:/porn
        - ${ROOT_MEDIA}/movies:/movies
        - ${ROOT_MEDIA}/movies4k:/movies4k
        - ${ROOT_MEDIA}/tv:/tv
        - ${ROOT_MEDIA}/other:/other
        - ${ROOT_MEDIA}/hentai:/hentai
        - ${ROOT_MEDIA}/porn_vr:/porn_vr
        - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai_comics
    environment:
        - VPN_ENABLED=wireguard
        - VPN_TYPE=openvpn
        - ENABLE_SSL=no
        - VPN_USERNAME=${NORD_USER}
        - VPN_PASSWORD=${NORD_PASSWORD}
        - WEBUI_USERNAME=root
        - WEBUI_PASSWORD=${PASSWORD}
        - PUID=${PUID}
        - PGID=${PGID}
        - LAN_NETWORK=192.168.8.10/24
        - 'NAME_SERVERS=1.1.1.1,1.0.0.1'
    ports:
        - '6789:6789'
        - '6791:6791'
    networks:
      - mariusz-network
    restart: unless-stopped
    image: dyonr/nzbgetvpn

  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    environment:
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/authelia:/config
    networks:
      - mariusz-network
    restart: unless-stopped

  xbvr:
    image: 'ghcr.io/xbapps/xbvr:latest'
    container_name: xbvr
    environment:
      - UI_USERNAME=root
      - UI_PASSWORD=${PASSWORD}
      - DEO_USERNAME=root
      - DEO_PASSWORD=${PASSWORD}
    volumes:
      - ${ROOT_MEDIA}/porn_vr:/videos
      - ${ROOT_APPDATA}/xbvr:/root/.config/
    ports:
      - "9999:9999"
    networks:
      - mariusz-network
    restart: unless-stopped

  jfa:
      container_name: jfa
      ports:
          - "8056:8056"
      volumes:
          - ${ROOT_APPDATA}/jfa-go:/data
          - ${ROOT_APPDATA}/jellyfin:/jf
          - '/etc/localtime:/etc/localtime:ro'
      image: hrfee/jfa-go
      restart: unless-stopped

  whisparr:
    container_name: whisparr
    image: cr.hotio.dev/hotio/whisparr
    ports:
      - "6969:6969"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/whisparr:/config
      - ${ROOT_MEDIA}/porn:/porn

networks:
  mariusz-network:
