services:
  nordvpn:
    container_name: GlueTun-Nord
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - "8082:8082" # QbitTorrent UI
      - "9091:9091" # Transmission
      - "51413:51413" # Transmision
      - "51413:51413/udp" # Transmision
      - "51420:51420" # QbitTorrent
      - "51420:51420/udp" # QbitTorrent
#      - "8085:8081" #metube
      - "8080:8080" # OpenWebUI
      - "11434:11434" # Ollama
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${NORD_U}
      - OPENVPN_PASSWORD=${NORD_P}
      - SERVER_REGIONS=Poland
      - VPN_TYPE=openvpn
      - FIREWALL_OUTBOUND_SUBNETS=192.168.8.0/24
    networks:
      - mariusz-network
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:nordvpn"
    container_name: QbitTorrent-Nord
    depends_on:
      - nordvpn
      - swag
    environment:
      - WEBUI_PORT=8082
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/qbittorrent:/config
      - ${ROOT_MEDIA}:/media_data
      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai_comics
      - ${ROOT_SSD}:/ssd
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/metube:/config
      - ${ROOT_MEDIA}/downloads/metube:/downloads
      - ${ROOT_MEDIA}/movies:/downloads/movies
      - ${ROOT_MEDIA}/tv:/downloads/tv
      - ${ROOT_MEDIA}/porn:/downloads/porn
      - "/etc/localtime:/etc/localtime:ro"
    ports:
        - 8085:8081
    networks:
      - mariusz-network
    depends_on:
      - swag

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/sonarr:/config
      - ${ROOT_MEDIA}:/media_data
    ports:
      - 8989:8989
    networks:
      - mariusz-network
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/radarr:/config
      - ${ROOT_MEDIA}:/media_data
    ports:
      - 7878:7878
    networks:
      - mariusz-network
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT_APPDATA}/bazarr:/config
      - ${ROOT_MEDIA}:/media_data
    ports:
      - 6767:6767
    networks:
      - mariusz-network
    restart: unless-stopped

  ombi:
    image: ghcr.io/linuxserver/ombi:development
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/ombi:/config
    ports:
      - 3579:3579
    networks:
      - mariusz-network
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      URL: januszex.net
      SUBDOMAINS: >
        www,
        bazarr,
        radarr,
        sonarr,
        qbittorrent,
        nextcloud,
        jellyfin,
        ombi,
        comicstreamer,
        prowlarr,
        xbvr,
        accounts,
        whisparr,
        metube,
        transmission,
        sabnzbd,
        duplicati,
        vue,
        files,
        openwebui,
        chat
      VALIDATION: http
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    networks:
      - mariusz-network
    restart: unless-stopped

  docker-host:
    image: qoomon/docker-host
    container_name: docker-host
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - mariusz-network
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - FFMPEG_ANALYZEDURATION=400M
      - FFMPEG_PROBESIZE=2G
    volumes:
      - ${ROOT_APPDATA}/jellyfin:/config
      - ${ROOT_MEDIA}/tv:/data/tv
      - ${ROOT_MEDIA}/movies:/data/movies
      - ${ROOT_MEDIA}/movies4k:/data/movies4k
      - ${ROOT_MEDIA}/downloads:/downloads
      - ${ROOT_MEDIA}/porn:/data/porn
      - ${ROOT_MEDIA}/music:/music
      - ${ROOT_MEDIA}/random:/random
      - ${ROOT_APPDATA}/jellyfin/config.json:/usr/share/jellyfin/web/config.json
    ports:
      - 8097:8096
    networks:
      - mariusz-network
    devices:
      - "/dev/dri:/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [video]
    restart: unless-stopped

  comicstreamer:
    container_name: comicstreamer
    image: mateuszkukiela/comicstreamer:latest
    volumes:
      - ${ROOT_APPDATA}/comicstreamer:/config
      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai
    ports:
      - 32500:32500
    networks:
      - mariusz-network
    restart: unless-stopped

  prowlarr:
      image: ghcr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      volumes:
        - ${ROOT_APPDATA}/prowlarr:/config
      ports:
        - 9696:9696
      networks:
        - mariusz-network
      restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/sabnzbd:/config
      - ${ROOT_MEDIA}:/media_data
      - ${ROOT_NEXTCLOUD}/robo/files/hentai:/hentai_comics
      - ${EXTERNAL_SSD}:/ssd
    ports:
      - 8089:8080
    networks:
      - mariusz-network
    restart: unless-stopped

  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    environment:
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/authelia:/config
    networks:
      - mariusz-network
    restart: unless-stopped

  jfa:
      container_name: jfa
      ports:
          - "8056:8056"
      volumes:
          - ${ROOT_APPDATA}/jfa-go:/data
          - ${ROOT_APPDATA}/jellyfin:/jf
          - '/etc/localtime:/etc/localtime:ro'
      image: hrfee/jfa-go
      restart: unless-stopped
      networks:
          - mariusz-network

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
        - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  homebridge:
    container_name: homebridge_ukasz
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${ROOT_APPDATA}/homebridge_ukasz:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - ${ROOT_APPDATA}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_APPDATA}/duplicati/config:/config
      - ${ROOT_BACKUPS}:/backups
      - ${ROOT_MARIUSZ}:/source
    ports:
      - 8200:8200
    networks:
      - mariusz-network
    restart: unless-stopped

  jf-vue:
    image: jellyfin/jellyfin-vue:unstable
    container_name: "jellyfin-vue-client"
    stdin_open: true
    tty: true
    ports:
      - 3831:80
    restart: unless-stopped
    environment:
      - DEFAULT_SERVERS=https://jellyfin.januszex.net
    networks:
      - mariusz-network

  filebrowser:
    container_name: filebrowser
    volumes:
        - ${ROOT_APPDATA}:/srv/appdata
        - ${ROOT_MEDIA}:/srv/media
        - ${ROOT_MARIUSZ}:/srv/mariusz
        - ${ROOT_APPDATA}/filebrowser/filebrowser.db:/database/filebrowser.db
        - ${ROOT_APPDATA}/filebrowser/settings.json:/config/settings.json
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    ports:
        - 8250:80
    image: filebrowser/filebrowser:s6
    networks:
      - mariusz-network
    restart: unless-stopped

  openwebui:
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
        - ${ROOT_APPDATA}/openwebui:/app/backend/data
    container_name: openwebui
    restart: always
    image: ghcr.io/open-webui/open-webui:cuda
    network_mode: "service:nordvpn"

  ollama:
    volumes:
      - ${ROOT_SSD}/ollama:/root/.ollama
    container_name: ollama
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    network_mode: "service:nordvpn"
    restart: unless-stopped

  whisperasr:
    container_name: whisperasr
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=faster_whisper
    ports:
      - 9000:9000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped
    networks:
      - mariusz-network

networks:
  mariusz-network:
