version: '3.3'
services:
  infrared:
    container_name: infrared
    restart: unless-stopped
    volumes:
      - ./infrared/configs/:/configs
    ports:
      - 25565:25565
    expose:
      - 25565
    image: haveachin/infrared:latest

  minecraft-ftb:
    restart: unless-stopped
    container_name: minecraft-ftb
    environment:
      - EULA=TRUE
      - TYPE=FTBA
      - FTB_MODPACK_ID=4
      - MEMORY=6G
      - ENABLE_AUTOPAUSE=TRUE
      - ONLINE_MODE=FALSE
      - OPS=robo,ukasz1337
      - SERVER_NAME=Feed The Ukasz
      - MOTD=Feed The Ukasz
      - MAX_TICK_TIME=-1
    ports:
      - 25569:25565
    volumes:
      - ${ROOT_APPDATA}/minecraft/minecraft-ftb:/data
    image: itzg/minecraft-server:java8-multiarch

  minecraft-ftb-backup:
    restart: unless-stopped
    container_name: minecraft-ftb-backup
    image: itzg/mc-backup
    environment:
      - BACKUP_INTERVAL=24h
      - PRUNE_BACKUPS_DAYS=7
      - PRUNE_RESTIC_RETENTION=--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75
    volumes:
      - ${ROOT_APPDATA}/minecraft/minecraft-ftb:/data:ro
      - ${ROOT_MEDIA}/minecraft/minecraft-ftb-backups:/backups
    network_mode: service:minecraft-ftb

  minecraft-bruno:
    restart: unless-stopped
    container_name: minecraft-bruno
    environment:
      - EULA=TRUE
      - TYPE=PAPER
      - MEMORY=2G
      - ENABLE_AUTOPAUSE=TRUE
      - ONLINE_MODE=FALSE
      - OPS=robo,ukasz1337
      - SERVER_NAME=Super Serwer Bruna
      - MOTD=Super Serwer Bruna
      - FORCE_REDOWNLOAD=true
      - MAX_TICK_TIME=-1
      - SPIGET_RESOURCES=57272,2124,274,241
    ports:
      - 25566:25565
      - 6969:8123
    volumes:
      - ${ROOT_APPDATA}/minecraft/minecraft-bruno:/data
    image: itzg/minecraft-server

  minecraft-bruno-backup:
    restart: unless-stopped
    container_name: minecraft-bruno-backup
    image: itzg/mc-backup
    environment:
      - BACKUP_INTERVAL=24h
      - PRUNE_BACKUPS_DAYS=7
      - PRUNE_RESTIC_RETENTION=--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75
    volumes:
      - ${ROOT_APPDATA}/minecraft/minecraft-bruno:/data:ro
      - ${ROOT_MEDIA}/minecraft/minecraft-bruno-backups:/backups
    network_mode: service:minecraft-bruno
