version: '3.9'
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - UMASK_SET=022
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - //home/mariusz/jellyfin:/config
      - /mnt/media/tv:/data/tv
      - /mnt/media/movies:/data/movies
      - /mnt/media/movies4k:/data/movies4k
      - /mnt/media/downloads:/downloads
      - /mnt/media/porn:/data/porn
      - /mnt/media/music:/music
      - /home/mariusz/jellyfin/config.json:/usr/share/jellyfin/web/config.json
    ports:
      - 8096:8096
    devices:
      - "/dev/dri:/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [video]
    restart: unless-stopped